### ISSUE TITLE
Prefix Features

### ISSUE THREAD

**Issue by Elemperor1** [the-crazyball/anomalousspace#60]
- Add in a way for people to see their prefix; maybe by mentioning the bot.

- Under every command panel it says "!s play", "!s start"; make it so their prefix is shown instead.

<img width="195" alt="Screen Shot 2022-07-14 at 8 48 22 PM" src="https://user-images.githubusercontent.com/48484869/179124739-e066344c-fcf7-4ea1-826a-7aa8ac09b005.png">

- Allow people to still use the "!s" prefix even when their own prefix is different.

**Comment by the-crazyball** [comment]
#1 - this exists already, has been there since the bot was created.
#2 - I think it should stay for everyone else to see that they can use !s since it's always active and usable. If we change it to their own prefix, then if someone new comes in and sees that it won't work for them.
#3 - this was fixed with issue #44
